### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by wirthual** [Lexycon/android-ws2801#2]
Hi,

thanks for sharing your project. 

Maybe you can add a license to enable better reuse or modification?

Regards
wirthual

**Comment by Lexycon** [comment]
Hi,

You're welcome! Done.

Regards
Lexycon

**Comment by wirthual** [comment]
Nice! If you now add the year and name in the License its even more perfect ;)

 Just Replace: 
Copyright {yyyy} {name of copyright owner}
with
Copyright 2017 Lexycon

Regards

**Comment by Lexycon** [comment]
Thanks for the hint :-)

Regards
